In [1]:
import pandas as pd
import requests

In [6]:
City_Name=input("Enter the City/ taluka  :")
Req=requests.get("https://api.openweathermap.org/data/2.5/weather?q={}&appid=1be6fe3a073779145b4ccfa2dad856ec".format(City_Name))

data=Req.json()
weather_data = {
            "City": data["name"],
            "Temperature (°C)": data["main"]["temp"],
             "Min_Temperature (°C)": data["main"]["temp_min"],
             "Max_Temperature (°C)": data["main"]["temp_max"],
             "Feels_Like (°C)": data["main"]["feels_like"],
             "Pressure (hpa)": data["main"]["pressure"],
            "Weather": data["weather"][0]["description"],
            "Humidity (%)": data["main"]["humidity"],
            "Wind Speed (m/s)": data["wind"]["speed"]}
weather_data


df=pd.DataFrame([weather_data])
print(df)
df.to_csv("City_Data",mode='a',header=not pd.io.common.file_exists("City_Data"),index=False)

Enter the City/ taluka  : goa

  City  Temperature (°C)  Min_Temperature (°C)  Max_Temperature (°C)  \
0  Goa            303.36                303.36                303.36

   Feels_Like (°C)  Pressure (hpa)        Weather  Humidity (%)  \
0           309.22            1008  broken clouds            72

   Wind Speed (m/s)
0              2.09

In [5]:
weather=pd.read_csv(("OneDrive/Desktop/weather Project Api/City_Data"),usecols=["City","Temperature (°C)","Min_Temperature (°C)","Max_Temperature (°C)","Feels_Like (°C)","Pressure (hpa)","Weather","Humidity (%)","Wind Speed (m/s)"])
weather

,City,Temperature (°C),Min_Temperature (°C),Max_Temperature (°C),Feels_Like (°C),Pressure (hpa),Weather,Humidity (%),Wind Speed (m/s)
0,Pune,303.46,303.46,303.46,303.73,1012,scattered clouds,44,1.22
1,Mumbai,306.14,303.09,306.14,310.94,1011,smoke,55,4.12
2,Ratnagiri,304.31,304.31,304.31,307.59,1010,scattered clouds,57,3.96
3,Dapoli,304.56,304.56,304.56,307.13,1010,overcast clouds,53,3.03
4,Shegaon,297.58,297.58,297.58,297.75,1012,overcast clouds,64,1.90
5,Nagpur,303.16,303.16,303.16,306.41,1011,haze,62,1.03
6,Satara,302.85,302.85,302.85,303.21,1012,scattered clouds,46,1.22
7,Kolhāpur,304.38,304.38,304.38,305.37,1010,clear sky,46,2.71
8,Sangli,304.53,304.53,304.53,305.06,1010,few clouds,43,2.23
9,Chinchwad,304.18,304.18,304.18,304.10,1010,scattered clouds,40,0.47
10,Amrāvati,299.67,299.67,299.67,299.67,1011,overcast clouds,59,0.78
11,Dhule,303.17,303.17,303.17,303.63,1011,scattered clouds,46,2.83
12,Jālna,300.67,300.67,300.67,301.74,1011,broken clouds,58,2.14

### Maharashtra cities data from Weather Api

In [1]:
import requests
import pandas as pd 

# List of cities from various talukas/cities in Maharashtra

city_name = [
    "Mumbai", "Mumbai", "Andheri", "Borivali", "Malad", "Colaba",
    "Pune", "Pimpri-Chinchwad", "Haveli", "Mulshi", "Khed", "Maval","Aundh","Junnar",
    "Nagpur", "Kamptee", "Narkhed", "Umred", "Saoner",
    "Nashik", "Nandgaon", "Dindori", "Trimbak", "Igatpuri",
    "Aurangabad", "Jalna", "Paithan", "Sillod", "Kannad",
    "Kolhapur", "Hatkanangale", "Shirol", "Karveer", "Radhanagari",
    "Solapur", "Barshi", "Karmala", "Pandharpur", "Mangalvedha",
    "Thane", "Kalyan", "Ulhasnagar", "Ambernath", "Badlapur", "Bhiwandi",
    "Satara", "Karad", "Khatav", "Wai", "Phaltan",
    "Sawantwadi", "Kudal", "Malvan", "Vengurla",
    "Chandrapur", "Ballarpur", "Warora", "Rajura", "Bhivpur",
    "Beed", "Patoda", "Georai", "Kaij", "Ashti",
    "Latur", "Ausa", "Nilanga", "Deoni", "Renapur",
    "Malkapur", "Chikhli", "Khamgaon", "Shegaon", "Jalgaon Jamod",
    "Jalna", "Badnapur", "Partur", "Mantha", "Jafrabad",
    "Ratnagiri", "Chiplun", "Dapoli", "Rajapur", "Khed",
    "Hingoli", "Aundha", "Kalamnuri", "Sengaon",
    "Wardha", "Arvi", "Deoli", "Karanja",
    "Yavatmal", "Pusad", "Arni", "Wani", "Digras",
    "Akola", "Murtizapur", "Patur", "Baranjala", "Telhara",
    "Amravati", "Morshi", "Chandur Bazar", "Achalpur", "Nandgaon Khandeshwar",
    "Alibag", "Uran", "Panvel", "Karjat", "Khalapur",
    "Washim", "Khamgaon", "Manora", "Pusad"]

API_Key="1be6fe3a073779145b4ccfa2dad856ec"

# List to hold all weather data
weather_data_list = []

# Fetch data for each city
for city in city_name:
    try:
        Req=requests.get("https://api.openweathermap.org/data/2.5/weather?q={}&appid=1be6fe3a073779145b4ccfa2dad856ec&units=metric"
.format(city))
        if Req.status_code == 200:
            data = Req.json()

            # Extract relevant weather data
            weather_data = {
                "City": data["name"],
                "Temperature (°C)": data["main"]["temp"],
                "Min_Temperature (°C)": data["main"]["temp_min"],
                "Max_Temperature (°C)": data["main"]["temp_max"],
                "Feels_Like (°C)": data["main"]["feels_like"],
                "Pressure (hpa)": data["main"]["pressure"],
                "Weather": data["weather"][0]["description"],
                "Humidity (%)": data["main"]["humidity"],
                "Wind Speed (m/s)": data["wind"]["speed"],
                "TimeZone (sec)": data["timezone"]
            }
            
            # Add the weather data for the current city to the list
            weather_data_list.append(weather_data)
        else:
             print(f"Error: Could not fetch data for {city}")
    except Exception as e:
        print(f"An error occurred while fetching data for {city}: {e}")

                                    
df = pd.DataFrame(weather_data_list) # Convert the list of weather data to a DataFrame
print(df)

# Save the DataFrame to a CSV file
df.to_csv("maharashtra_weather_data3.csv", index=False)

Error: Could not fetch data for Malad
Error: Could not fetch data for Colaba
Error: Could not fetch data for Maval
Error: Could not fetch data for Hatkanangale
Error: Could not fetch data for Karveer
Error: Could not fetch data for Radhanagari
Error: Could not fetch data for Mangalvedha
Error: Could not fetch data for Bhivpur
Error: Could not fetch data for Deoni
Error: Could not fetch data for Renapur
Error: Could not fetch data for Jafrabad
Error: Could not fetch data for Aundha
Error: Could not fetch data for Sengaon
Error: Could not fetch data for Murtizapur
Error: Could not fetch data for Baranjala
         City  Temperature (°C)  Min_Temperature (°C)  Max_Temperature (°C)  \
0      Mumbai             31.99                 29.94                 31.99
1      Mumbai             31.99                 29.94                 31.99
2     Andheri             19.57                 19.57                 19.57
3    Borivali             29.90                 29.90                 30.95
4        Pune             28.51                 28.51                 28.51
..        ...               ...                   ...                   ...
96   Khalapur             32.16                 32.16                 32.16
97     Wāshīm             26.20                 26.20                 26.20
98   Khāmgaon             26.83                 26.83                 26.83
99     Manora             27.63                 27.63                 27.63
100     Pusad             27.19                 27.19                 27.19

     Feels_Like (°C)  Pressure (hpa)          Weather  Humidity (%)  \
0              31.76            1011            smoke            37
1              31.76            1011            smoke            37
2              18.29            1011  overcast clouds            27
3              30.60            1010            smoke            48
4              27.43            1010       few clouds            29
..               ...             ...              ...           ...
96             31.00            1009       few clouds            30
97             26.20            1012       few clouds            19
98             26.04            1012        clear sky            22
99             26.55            1011    broken clouds            22
100            26.18            1011        clear sky            19

     Wind Speed (m/s)  TimeZone (sec)
0                4.63           19800
1                4.63           19800
2                1.99           20700
3                4.63           19800
4                2.20           19800
..                ...             ...
96               2.75           19800
97               2.58           19800
98               2.22           19800
99               1.53           19800
100              2.70           19800

[101 rows x 10 columns]